Repository openshift/cluster-config-operator, pull requests merged in 2019-05, with the labels that each got.

#55 Revert "manually create a CRD that should be generated"
  manifests/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  manifests/0000_05_config-operator_03_rolebindingrestrictions.crd.yaml
  manifests/0000_05_config-operator_03_scc.crd.yaml
Labels: approved, size/L

#56 TEST PR DO NOT MERGE
  manifests/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/types.go
Labels: do-not-merge/hold, size/L

#57 Add RoleBindingRestriction CRD
  manifests/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
Labels: approved, lgtm, size/L

#39 add empty CRs
  empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
Labels: approved, lgtm, size/XS

#61 Bump for RBR CRD, add nullables, Namespaced
  glide.lock
  manifests/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/golang.org/x/tools/go/analysis/analysis.go
  vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go
  vendor/golang.org/x/tools/internal/span/span.go
Labels: approved, lgtm, size/L

#62 Remove status subresource from SCC and RBR crd
  manifests/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  manifests/0000_03_security-openshift_01_scc.crd.yaml
Labels: approved, lgtm, size/XS
