Repository openshift/cluster-config-operator, pull requests merged in 2019-04, with the labels that each got.

#25 add cluster resource quota resources
  manifests/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
Labels: approved, lgtm, size/M

#31 crq: add status sub-resource
  manifests/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
Labels: approved, lgtm, size/XS

#36 add empty CRs
  Dockerfile
  Dockerfile.rhel7
  empty-resources/0000_05_config-operator_02_ingress.cr.yaml
  empty-resources/0000_05_config-operator_02_network.cr.yaml
  empty-resources/0000_05_config-operator_02_oauth.cr.yaml
  empty-resources/0000_05_config-operator_02_project.cr.yaml
  empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
  manifests/0000_05_config-operator_01_featuregate.crd.yaml
  manifests/0000_05_config-operator_01_scheduler.crd.yaml
Labels: approved, lgtm, size/M

#37 add empty CRs
  empty-resources/0000_05_config-operator_02_image.cr.yaml
  empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
Labels: approved, lgtm, size/S

#40 add empty CRs
  empty-resources/0000_05_config-operator_02_dns.cr.yaml
Labels: approved, lgtm, size/XS

#43 remove possibly failing CRs
  empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
  empty-resources/0000_05_config-operator_02_authentication.cr.yaml
  empty-resources/0000_05_config-operator_02_build.cr.yaml
  empty-resources/0000_05_config-operator_02_console.cr.yaml
Labels: approved, size/S

#45 Add back all empty custom resources (including authentication)
  empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
  empty-resources/0000_05_config-operator_02_authentication.cr.yaml
  empty-resources/0000_05_config-operator_02_build.cr.yaml
  empty-resources/0000_05_config-operator_02_console.cr.yaml
Labels: approved, lgtm, size/S

#47 rbac: add aggregate-to-cluster-reader permissions
  manifests/0000_05_config-operator_02_config.clusterrole.yaml
Labels: approved, lgtm, size/M

#48 add node-selector annotation
  manifests/0000_05_config-operator_01_openshift-config-managed-ns.yaml
  manifests/0000_05_config-operator_01_openshift-config-ns.yaml
Labels: approved, lgtm, size/XS

#49 Move component to an appropriate upgrade order (config-operator)
  manifests/0000_10_config-operator_01_apiserver.crd.yaml
  manifests/0000_10_config-operator_01_authentication.crd.yaml
  manifests/0000_10_config-operator_01_build.crd.yaml
  manifests/0000_10_config-operator_01_console.crd.yaml
  manifests/0000_10_config-operator_01_dns.crd.yaml
  manifests/0000_10_config-operator_01_featuregate.crd.yaml
  manifests/0000_10_config-operator_01_image.crd.yaml
  manifests/0000_10_config-operator_01_infrastructure.crd.yaml
  manifests/0000_10_config-operator_01_ingress.crd.yaml
  manifests/0000_10_config-operator_01_network.crd.yaml
  manifests/0000_10_config-operator_01_oauth.crd.yaml
  manifests/0000_10_config-operator_01_openshift-config-managed-ns.yaml
  manifests/0000_10_config-operator_01_openshift-config-ns.yaml
  manifests/0000_10_config-operator_01_project.crd.yaml
  manifests/0000_10_config-operator_01_scheduler.crd.yaml
  manifests/0000_10_config-operator_02_config.clusterrole.yaml
  manifests/0000_10_quota-openshift_01_clusterresourcequota.crd.yaml
Labels: approved, lgtm, size/XS
