Repository openshift/cluster-config-operator, pull requests merged in 2019-02, with the labels that each got.

#4 add project config crd
  manifests/0000_05_config-operator_01_project.crd.yaml
Labels: lgtm, size/S

#9 add authentication CRD
  manifests/0000_05_config-operator_01_authentication.crd.yaml
Labels: lgtm, size/S

#11 Add Console CRD
  manifests/0000_05_config-operator_01_console.crd.yaml
Labels: lgtm, size/S

#12 README update
  README.md
Labels: size/XS

#14 add image references
  manifests/image-references
Labels: approved, lgtm, size/XS

#16 create bootstrap-manifests directory
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/S
