Repository openshift/cluster-config-operator, pull requests merged in 2019-08, with the labels that each got.

#85 Add mfojtik as approver
  OWNERS
Labels: approved, lgtm, size/XS

#75 [release-4.1] Bug 1732934: remove defaultservingcert description in apiserver config
  glide.lock
  glide.yaml
  manifests/0000_10_config-operator_01_apiserver.crd.yaml
  manifests/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-protobuf.sh
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/change_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#88 Bump to golang 1.12 and update Makefile image target
  Dockerfile
  Dockerfile.rhel7
  Makefile
Labels: approved, lgtm, size/S
