Repository openshift/cluster-config-operator, pull requests merged in 2019-07, with the labels that each got.

#71 specify status subresources for resources with empty status
  manifests/0000_10_config-operator_01_apiserver.crd.yaml
  manifests/0000_10_config-operator_01_build.crd.yaml
  manifests/0000_10_config-operator_01_dns.crd.yaml
  manifests/0000_10_config-operator_01_featuregate.crd.yaml
  manifests/0000_10_config-operator_01_ingress.crd.yaml
  manifests/0000_10_config-operator_01_project.crd.yaml
  manifests/0000_10_config-operator_01_scheduler.crd.yaml
Labels: approved, lgtm, size/S

#72 Add empty Proxy resource
  empty-resources/0000_05_config-operator_02_proxy.cr.yaml
Labels: approved, lgtm, size/XS

#73 Generate operator/v1alpha1 CRDs, update for https://github.com/openshift/api/pull/384
  Makefile
  glide.lock
  manifests/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/beorn7/perks/VERSION
  vendor/github.com/beorn7/perks/go.mod
  vendor/github.com/beorn7/perks/histogram/histogram_test.go
  vendor/github.com/beorn7/perks/quantile/stream.go
  vendor/github.com/beorn7/perks/quantile/stream_test.go
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/types_console_link.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/manifest.go
  vendor/github.com/prometheus/client_model/AUTHORS.md
  vendor/github.com/prometheus/client_model/CONTRIBUTING.md
  vendor/github.com/prometheus/client_model/MAINTAINERS.md
  vendor/github.com/prometheus/client_model/Makefile
  vendor/github.com/prometheus/client_model/go.mod
  vendor/github.com/prometheus/client_model/go.sum
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/client_model/metrics.proto
  vendor/github.com/prometheus/client_model/ruby/README.md
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
Labels: approved, lgtm, size/XXL

#77 Attempt to fix upgrades with Proxy object
  manifests/0000_03_config-operator_01_proxy.crd.yaml
Labels: approved, lgtm, size/XS
