Repository openshift/cluster-config-operator, pull requests merged in 2019-10, with the labels that each got.

#93 Bug 1754640: Update CRD manifests for structural schema requirements
  .gitignore
  Makefile
  manifests/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  manifests/0000_03_config-operator_01_operatorhub.crd.yaml
  manifests/0000_03_config-operator_01_proxy.crd.yaml
  manifests/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  manifests/0000_03_security-openshift_01_scc.crd.yaml
  manifests/0000_10_config-operator_01_apiserver.crd.yaml
  manifests/0000_10_config-operator_01_authentication.crd.yaml
  manifests/0000_10_config-operator_01_build.crd.yaml
  manifests/0000_10_config-operator_01_console.crd.yaml
  manifests/0000_10_config-operator_01_dns.crd.yaml
  manifests/0000_10_config-operator_01_featuregate.crd.yaml
  manifests/0000_10_config-operator_01_image.crd.yaml
  manifests/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  manifests/0000_10_config-operator_01_infrastructure.crd.yaml
  manifests/0000_10_config-operator_01_ingress.crd.yaml
  manifests/0000_10_config-operator_01_network.crd.yaml
  manifests/0000_10_config-operator_01_oauth.crd.yaml
  manifests/0000_10_config-operator_01_project.crd.yaml
  manifests/0000_10_config-operator_01_scheduler.crd.yaml
  manifests/0000_10_quota-openshift_01_clusterresourcequota.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#97 Enable TLS1.3 for go build
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#95 Migrate console extensions CRDs from console-operator
  Makefile
  manifests/0000_10_config-operator_01_consoleclidownload.crd.yaml
  manifests/0000_10_config-operator_01_consoleexternalloglink.crd.yaml
  manifests/0000_10_config-operator_01_consolelink.crd.yaml
  manifests/0000_10_config-operator_01_consolenotification.crd.yaml
Labels: approved, lgtm, size/L

#98 Fix local image build
  .dockerignore
Labels: approved, lgtm, size/XS

#100 Makefile allow passing image tag to 'make images'
  Makefile
Labels: approved, lgtm, size/XS

#103 Revert "Migrate console extensions CRDs from console-operator"
  Makefile
  manifests/0000_10_config-operator_01_consoleclidownload.crd.yaml
  manifests/0000_10_config-operator_01_consoleexternalloglink.crd.yaml
  manifests/0000_10_config-operator_01_consolelink.crd.yaml
  manifests/0000_10_config-operator_01_consolenotification.crd.yaml
Labels: approved, lgtm, size/L

#107 Add soltysh to approvers
  OWNERS
Labels: approved, lgtm, size/XS
