Repository openshift/cluster-config-operator, pull requests merged in 2020-06, with the labels that each got.

#134 Fix event spam in kube cloud config
  pkg/operator/kube_cloud_config/controller.go
Labels: approved, lgtm

#136 Bug 1847455: Fix Dockerfiles
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#138 [4.4] Bug 1847457: Fix Dockerfiles
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#137 [4.5] Bug 1847456: Fix Dockerfiles
  Dockerfile
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, group-lead-approved, lgtm

#131 Bug 1825194: oc explain still shows "The default is auth.openshift.io"
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#139 bump(openshift/api): Add new field for access token inactivity timeout in OAuth config
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/install.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/register.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/modules.txt
Labels: approved, lgtm

#133 kube_cloud_config: support for other Azure cloud environments
  pkg/operator/kube_cloud_config/azure.go
  pkg/operator/kube_cloud_config/azure_test.go
  pkg/operator/kube_cloud_config/controller.go
  pkg/operator/kube_cloud_config/controller_test.go
Labels: approved, lgtm
