Repository openshift/cluster-config-operator, pull requests merged in 2020-04, with the labels that each got.

#118 operator: add server to serve metrics and healthz
  manifests/0000_30_config-operator_01_prometheusrole.yaml
  manifests/0000_30_config-operator_02_prometheusrolebinding.yaml
  manifests/0000_30_config-operator_02_service.yaml
  manifests/0000_30_config-operator_03_servicemonitor.yaml
  manifests/0000_30_config-operator_07_deployment.yaml
Labels: approved, lgtm

#122 manifests: fix metrics labels
  manifests/0000_30_config-operator_02_service.yaml
  manifests/0000_30_config-operator_03_servicemonitor.yaml
Labels: approved, lgtm

#123 version: fix build_info metric reporting
  go.mod
  go.sum
  pkg/version/version.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: approved, lgtm

#125 vendor: bump to get infra status subresource
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#126 Bug 1825944: kube_cloud_config: enforce the target key in config map to cloud.conf
  pkg/operator/kube_cloud_config/aws.go
  pkg/operator/kube_cloud_config/aws_test.go
  pkg/operator/kube_cloud_config/controller.go
  pkg/operator/kube_cloud_config/controller_test.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#129 Bug 1828457: bump(*): vendor update
  go.mod
  go.sum
  pkg/dependencymagnet/doc.go
  vendor/github.com/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/CONTRIBUTING.md
  vendor/github.com/go-bindata/go-bindata/LICENSE
  vendor/github.com/go-bindata/go-bindata/Makefile
  vendor/github.com/go-bindata/go-bindata/README.md
  vendor/github.com/go-bindata/go-bindata/_config.yml
  vendor/github.com/go-bindata/go-bindata/asset.go
  vendor/github.com/go-bindata/go-bindata/bytewriter.go
  vendor/github.com/go-bindata/go-bindata/config.go
  vendor/github.com/go-bindata/go-bindata/convert.go
  vendor/github.com/go-bindata/go-bindata/debug.go
  vendor/github.com/go-bindata/go-bindata/doc.go
  vendor/github.com/go-bindata/go-bindata/file.go
  vendor/github.com/go-bindata/go-bindata/release.go
  vendor/github.com/go-bindata/go-bindata/restore.go
  vendor/github.com/go-bindata/go-bindata/stringwriter.go
  vendor/github.com/go-bindata/go-bindata/toc.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/main.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/version.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
