Repository openshift/cluster-config-operator, pull requests merged in 2020-09, with the labels that each got.

#152 Bug 1878648: oauth: audit log oauthaccesstokens if fresh 4.6 install
  empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#156 bug 1871890: add current profile annotations to CVO manifests
  manifests/0000_10_config-operator_01_openshift-config-managed-ns.yaml
  manifests/0000_10_config-operator_01_openshift-config-ns.yaml
  manifests/0000_10_config-operator_02_config.clusterrole.yaml
  manifests/0000_30_config-operator_00_namespace.yaml
  manifests/0000_30_config-operator_01_operator.cr.yaml
  manifests/0000_30_config-operator_01_prometheusrole.yaml
  manifests/0000_30_config-operator_02_prometheusrolebinding.yaml
  manifests/0000_30_config-operator_02_service.yaml
  manifests/0000_30_config-operator_03_servicemonitor.yaml
  manifests/0000_30_config-operator_04_roles.yaml
  manifests/0000_30_config-operator_05_serviceaccount.yaml
  manifests/0000_30_config-operator_07_deployment.yaml
  manifests/0000_30_config-operator_08_clusteroperator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#153 Bug 1879492: Add secure access token annotation controller to handle downgrade from 4.6
  pkg/operator/aws_platform_service_location/controller.go
  pkg/operator/secureaccesstoken/controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#155 Bug 1880304: Fix bug in reflector not recovering from "Too large resource version"
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#158 Bug 1878040: Add validation for logLevel
  go.mod
  go.sum
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#157 Bug 1883458: add rangeallocation CRD
  Dockerfile.rhel7
  go.mod
  go.sum
  pkg/dependencymagnet/doc.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/securityinternal/v1/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml
  vendor/github.com/openshift/api/securityinternal/v1/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml-patch
  vendor/github.com/openshift/api/securityinternal/v1/doc.go
  vendor/github.com/openshift/api/securityinternal/v1/register.go
  vendor/github.com/openshift/api/securityinternal/v1/types.go
  vendor/github.com/openshift/api/securityinternal/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/securityinternal/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#159 Bug 1883898: add service ca operator to log level controller resource list
  pkg/operator/operatorloglevel/loglevel_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
