Repository openshift/cluster-config-operator, pull requests merged in 2021-01, with the labels that each got.

#169 Bug 1915473: Annotate manifests for single-node-developer cluster profile
  empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
  empty-resources/0000_05_config-operator_02_authentication.cr.yaml
  empty-resources/0000_05_config-operator_02_build.cr.yaml
  empty-resources/0000_05_config-operator_02_console.cr.yaml
  empty-resources/0000_05_config-operator_02_dns.cr.yaml
  empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
  empty-resources/0000_05_config-operator_02_image.cr.yaml
  empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
  empty-resources/0000_05_config-operator_02_ingress.cr.yaml
  empty-resources/0000_05_config-operator_02_network.cr.yaml
  empty-resources/0000_05_config-operator_02_oauth.cr.yaml
  empty-resources/0000_05_config-operator_02_operatorhub.cr.yaml
  empty-resources/0000_05_config-operator_02_project.cr.yaml
  empty-resources/0000_05_config-operator_02_proxy.cr.yaml
  empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
  manifests/0000_10_config-operator_01_openshift-config-managed-ns.yaml
  manifests/0000_10_config-operator_01_openshift-config-ns.yaml
  manifests/0000_10_config-operator_02_config.clusterrole.yaml
  manifests/0000_30_config-operator_00_namespace.yaml
  manifests/0000_30_config-operator_01_operator.cr.yaml
  manifests/0000_30_config-operator_01_prometheusrole.yaml
  manifests/0000_30_config-operator_02_prometheusrolebinding.yaml
  manifests/0000_30_config-operator_02_service.yaml
  manifests/0000_30_config-operator_03_servicemonitor.yaml
  manifests/0000_30_config-operator_04_roles.yaml
  manifests/0000_30_config-operator_05_serviceaccount.yaml
  manifests/0000_30_config-operator_07_deployment.yaml
  manifests/0000_30_config-operator_08_clusteroperator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#174 Bug 1890038: update AWS platform status migration controller for all platforms
  pkg/operator/migration_platform_status/OWNERS
  pkg/operator/migration_platform_status/controller.go
  pkg/operator/migration_platform_status/controller_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#179 Bug 1905573: [release 4.6] Add warning of the consequences of changing bound token issuer
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
