Repository openshift/cluster-config-operator, pull requests merged in 2021-04, with the labels that each got.

#166 Add IBM Cloud managed annotations to CVO manifests
  empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
  empty-resources/0000_05_config-operator_02_authentication.cr.yaml
  empty-resources/0000_05_config-operator_02_build.cr.yaml
  empty-resources/0000_05_config-operator_02_console.cr.yaml
  empty-resources/0000_05_config-operator_02_dns.cr.yaml
  empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
  empty-resources/0000_05_config-operator_02_image.cr.yaml
  empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
  empty-resources/0000_05_config-operator_02_ingress.cr.yaml
  empty-resources/0000_05_config-operator_02_network.cr.yaml
  empty-resources/0000_05_config-operator_02_oauth.cr.yaml
  empty-resources/0000_05_config-operator_02_operatorhub.cr.yaml
  empty-resources/0000_05_config-operator_02_project.cr.yaml
  empty-resources/0000_05_config-operator_02_proxy.cr.yaml
  empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
  manifests/0000_10_config-operator_01_openshift-config-managed-ns.yaml
  manifests/0000_10_config-operator_01_openshift-config-ns.yaml
  manifests/0000_10_config-operator_02_config.clusterrole.yaml
  manifests/0000_30_config-operator_00_namespace.yaml
  manifests/0000_30_config-operator_01_operator.cr.yaml
  manifests/0000_30_config-operator_01_prometheusrole.yaml
  manifests/0000_30_config-operator_02_prometheusrolebinding.yaml
  manifests/0000_30_config-operator_02_service.yaml
  manifests/0000_30_config-operator_03_servicemonitor.yaml
  manifests/0000_30_config-operator_04_roles.yaml
  manifests/0000_30_config-operator_05_serviceaccount.yaml
Labels: approved, lgtm

#191 Bug 1949145: Add user facing priority class
  manifests/0000_50_config-operator_09_user-priority-class.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#193 Bug 1949145: Add missing annotations to upc
  manifests/0000_50_config-operator_09_user-priority-class.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#190 Add management workload annotations
  manifests/0000_30_config-operator_00_namespace.yaml
  manifests/0000_30_config-operator_07_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#195 Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#197 Bug 1878199: remove log level normalizer
  pkg/operator/operatorloglevel/loglevel_controller.go
  pkg/operator/operatorloglevel/loglevel_controller_test.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#194 Rename workload annotations
  manifests/0000_30_config-operator_07_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#200 Bug 1954152: vendor: bump to the latest openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
