Repository openshift/cluster-config-operator, pull requests merged in 2022-05, with the labels that each got.

#248 manifests/deployment: comply to restricted pod security level
  manifests/0000_30_config-operator_07_deployment.yaml
Labels: lgtm, approved

#252 Bug 2075551: [release-4.9] backport api to commit 019a246c52
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#245 Bug 2082763: Drop the OperatorHub CR instance
  empty-resources/0000_05_config-operator_02_operatorhub.cr.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#253 Update images to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: lgtm, approved
