Repository openshift/cluster-config-operator, pull requests merged in 2023-10, with the labels that each got.

#357 OCPVE-708: feat: bump(api)
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.clusterversion.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/operator/v1/0000_80_machine-config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/stable.machineconfiguration.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#359 Remove AdmissionWebhookMatchConditions feature gate
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.ingresscontroller.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#363 [release-4.14] OCPBUGS-20439: Remove Build CRD
  empty-resources/0000_05_config-operator_02_build.cr.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_openshift-controller-manager-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.build.testsuite.yaml
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#360 OCPBUGS-20164: Remove Build CRD
  empty-resources/0000_05_config-operator_02_build.cr.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/0000_10_openshift-controller-manager-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.build.testsuite.yaml
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#358 Enable ValidatingAdmissionPolicy in TechPreviewNoUpgrade.
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.ingresscontroller.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#364 CFE-887: Bump openshift/api to add DNSNameResolver.
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/network/.codegen.yaml
  vendor/github.com/openshift/api/network/install.go
  vendor/github.com/openshift/api/network/v1alpha1/0000_70_dnsnameresolver_00-customnoupgrade.crd.yaml
  vendor/github.com/openshift/api/network/v1alpha1/0000_70_dnsnameresolver_00-customnoupgrade.crd.yaml-patch
  vendor/github.com/openshift/api/network/v1alpha1/0000_70_dnsnameresolver_00-techpreview.crd.yaml
  vendor/github.com/openshift/api/network/v1alpha1/0000_70_dnsnameresolver_00-techpreview.crd.yaml-patch
  vendor/github.com/openshift/api/network/v1alpha1/Makefile
  vendor/github.com/openshift/api/network/v1alpha1/custom.dnsnameresolver.testsuite.yaml
  vendor/github.com/openshift/api/network/v1alpha1/doc.go
  vendor/github.com/openshift/api/network/v1alpha1/register.go
  vendor/github.com/openshift/api/network/v1alpha1/techpreview.dnsnameresolver.testsuite.yaml
  vendor/github.com/openshift/api/network/v1alpha1/types_dnsnameresolver.go
  vendor/github.com/openshift/api/network/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#365 OCPBUGS-21781: Update openshift/api package to latest version
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#369 [release-4.14]: OCPBUGS-21286: bump library-go to include switch to HTTP/1.1
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
