Repository openshift/cluster-config-operator, pull requests merged in 2023-06, with the labels that each got.

#317 Update openshift/api to disable EventedPLEG featuregate in techpreview
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#309 remove dead flag for file
  pkg/cmd/render/render.go
Labels: lgtm, approved

#323 SPLAT-1099: bump openshift/api for vSphere static IP feature gate and platform spec
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/types_provider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#324 stomp the latencysensitive featureset for equivalent default
  pkg/operator/removelatencysensitive/OWNERS
  pkg/operator/removelatencysensitive/removelatencysensitive_controller.go
  pkg/operator/removelatencysensitive/removelatencysensitive_controller_test.go
  pkg/operator/starter.go
Labels: lgtm, approved
