Repository openshift/cluster-config-operator, pull requests merged in 2023-11, with the labels that each got.

#371 [release-4.14] OCPBUGS-21653: Update openshift/api package to latest version
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#361 NO-JIRA: pkg/cmd/render/config: Remove ReadFeatureGateV1OrDie
  pkg/cmd/render/config.go
Labels: lgtm, approved, jira/valid-reference

#373 [release-4.12]: OCPBUGS-21245: bump library-go to include switch to HTTP/1.1
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#377 MON-3480: Add MetricsServer FeatureGate
  go.mod
  go.sum
  vendor/github.com/openshift/api/Dockerfile.rhel8
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/machine/v1alpha1/types_openstack.go
  vendor/github.com/openshift/api/machine/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#380 Allow split rendering between cluster-config and openshift/api
  manifests/0000_10_config-operator_08_clusteroperator.yaml
  pkg/cmd/render/render.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#381 create parent dir for output
  pkg/cmd/render/render.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#378 SPLAT-1272: Update for Nutanix failure domains api changes
  go.mod
  go.sum
  vendor/github.com/openshift/api/Dockerfile.rhel8
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/stable.config.testsuite.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/authenticationspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/baremetalplatformspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/baremetalplatformstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/ibmcloudserviceendpoint.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/nutanixfailuredomain.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/nutanixplatformspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/nutanixresourceidentifier.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/oidcprovider.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/openstackplatformspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/openstackplatformstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/platformspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/prefixedclaimmapping.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/tokenclaimmapping.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/tokenclaimmappings.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/tokenclaimvalidationrule.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/tokenissuer.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/tokenrequiredclaim.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/usernameclaimmapping.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/usernameprefix.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vsphereplatformspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/vsphereplatformstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/internal/internal.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#382 create manifest directory during rendering
  pkg/cmd/render/render.go
Labels: lgtm, approved, jira/valid-reference

#386 CNF-10479:Bump up api to pull mixed cpu allocation feature gate
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#379 yield CRDs and empty resource rendering to api imge
  Dockerfile.rhel7
Labels: do-not-merge/hold, approved

#349 read featuregates from openshift/api
  manifests/0000_10_config-operator_07_deployment.yaml
  manifests/image-references
  pkg/cmd/operator/cmd.go
  pkg/cmd/render/config.go
  pkg/operator/featuregates/featuregate_controller.go
  pkg/operator/starter.go
Labels: lgtm, do-not-merge/hold, approved
