Repository openshift/cluster-config-operator, pull requests merged in 2023-05, with the labels that each got.

#299 Require consistency in rendered artifacts
  go.mod
  go.sum
  pkg/cmd/render/render.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug

#301 Update API and library-go
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/render/render.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug

#303 OCPBUGS-6266: Rename config-operator_00_namespace run level to 00
  manifests/0000_00_config-operator_00_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#311 Update github.com/openshift/api to pull in feature gates
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#312 Update github.com/openshift/api to pull in evented pleg and sigstore feature flags
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug
