Repository openshift/cluster-config-operator, pull requests merged in 2024-01, with the labels that each got.

#397 Revert "OCPBUGS-26541: remove duplicate manifests in image"
  Dockerfile.rhel7
  empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
  empty-resources/0000_05_config-operator_02_authentication.cr.yaml
  empty-resources/0000_05_config-operator_02_console.cr.yaml
  empty-resources/0000_05_config-operator_02_dns.cr.yaml
  empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
  empty-resources/0000_05_config-operator_02_image.cr.yaml
  empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
  empty-resources/0000_05_config-operator_02_ingress.cr.yaml
  empty-resources/0000_05_config-operator_02_network.cr.yaml
  empty-resources/0000_05_config-operator_02_oauth.cr.yaml
  empty-resources/0000_05_config-operator_02_project.cr.yaml
  empty-resources/0000_05_config-operator_02_proxy.cr.yaml
  empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
  empty-resources/0000_10_config-operator_02_node.cr.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#398 NO-JIRA: add inert featuregate files to allow diff against later releases
  manifests/0000_50_cluster-config-api_featureGate-Default.yaml
  manifests/0000_50_cluster-config-api_featureGate-TechPreviewNoUpgrade.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#399 OCPBUGS-26541: remove duplicate manifests in image
  Dockerfile.rhel7
  empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
  empty-resources/0000_05_config-operator_02_authentication.cr.yaml
  empty-resources/0000_05_config-operator_02_console.cr.yaml
  empty-resources/0000_05_config-operator_02_dns.cr.yaml
  empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
  empty-resources/0000_05_config-operator_02_image.cr.yaml
  empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
  empty-resources/0000_05_config-operator_02_ingress.cr.yaml
  empty-resources/0000_05_config-operator_02_network.cr.yaml
  empty-resources/0000_05_config-operator_02_oauth.cr.yaml
  empty-resources/0000_05_config-operator_02_project.cr.yaml
  empty-resources/0000_05_config-operator_02_proxy.cr.yaml
  empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
  empty-resources/0000_10_config-operator_02_node.cr.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-reference

#401 OCPBUGS-28621: Add required PSa labels
  manifests/0000_10_config-operator_01_openshift-config-ns.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
